substitutions:
  device_name: 'esphome-web-b8993c'
  friendly_name: 'BMT01 interface'
  device_description: "Bluetooth interface to BMT01 thermoprobe"
  project_version: "0.0.1"
  log_level: DEBUG
  mac_address: "12:F1:0A:04:27:D0"
  client_id: "bmt01"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: ${log_level}

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

globals:
  - id: ble_client_connected
    type: bool
    initial_value: 'false'

ble_client:
  - mac_address: ${mac_address}
    id: ${client_id}
    auto_connect: true
    on_connect:
      then:
        - lambda: |-
            id(ble_client_connected) = true;
            ESP_LOGD("ble_client_lambda", "${friendly_name}");
        - delay: 5s           
    on_disconnect:
      then:
        - lambda: |-
            id(ble_client_connected) = false;
            ESP_LOGD("ble_client_lambda", "${friendly_name}");     
        
binary_sensor:
  # Presence based on MAC address
  - platform: ble_presence
    mac_address: ${mac_address}
    name: "${friendly_name} BLE Status"

  - platform: template
    name: '${friendly_name} Connection'
    id: ble_connection
    lambda: 'return id(ble_client_connected);'    

sensor:
  # RSSI based on MAC address
  - platform: ble_rssi
    mac_address: ${mac_address} 
    name: "${friendly_name} BLE RSSI" 

  - platform: ble_client
    type: characteristic
    ble_client_id: ${client_id}
    name: "BMT01 battery level"
    service_uuid: '0000180F-0000-1000-8000-00805f9b34fb'
    characteristic_uuid: '00002A19-0000-1000-8000-00805f9b34fb'
    icon: 'mdi:battery'
    unit_of_measurement: '%'

  - platform: ble_client
    type: characteristic
    ble_client_id: ${client_id}
    id: charbbb1
    name: 'Characteristic bbb1'
    update_interval: 30s
    notify: True
    service_uuid: '0000aaaa-0000-1000-8000-00805f9b34fb'
    characteristic_uuid: '0000bbb1-0000-1000-8000-00805f9b34fb'

  - platform: ble_client
    type: characteristic
    ble_client_id: ${client_id}
    id: charbbb3
    update_interval: 30s
    notify: True
    name: 'Characteristic bbb3'
    service_uuid: '0000aaaa-0000-1000-8000-00805f9b34fb'
    characteristic_uuid: '0000bbb3-0000-1000-8000-00805f9b34fb'
    